version: '3.8'

services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  nocodb:
    image: nocodb/nocodb
  #  environment:
  #    DATABASE_URL: "postgres://postgres:postgres@postgres:5432/mydb"
    ports:
      - "8010:8010"
    depends_on:
      - postgres

  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    environment:
      NODE_ENV: production
    depends_on:
      - postgres
    command: npm run dev

volumes:
  postgres_data: