#:schema node_modules/wrangler/config-schema.json
name = "learn-to-bank-admin-console"
compatibility_date = "2024-09-09"
pages_build_output_dir = "./build/client"
compatibility_flags = [ "nodejs_compat_v2" ]

kv_namespaces = [
  { binding = "firebase_storage", id = "f2826afd4c764a229a642e2746c2a1ea" }
]

[[d1_databases]]
binding = "DB"
database_name = "learn-to-bank"
database_id = "9a1156c4-12e9-4292-8ab3-198355650df6"

######## PREVIEW environment config ########

[[env.preview.kv_namespaces]]
binding = "firebase_storage"
id = "f2826afd4c764a229a642e2746c2a1ea"

[[env.preview.d1_databases]]
binding = "DB"
database_name = "learn-to-bank"
database_id = "9a1156c4-12e9-4292-8ab3-198355650df6"

[env.preview.vars]
VITE_FIREBASE_API_KEY="AIzaSyArgMsHrQipciY8o_wB4_3t3YLmqwjK8ME"
VITE_FIREBASE_AUTH_DOMAIN="learn-to-bank.firebaseapp.com"
VITE_FIREBASE_PROJECT_ID="learn-to-bank"
VITE_FIREBASE_STORAGE_BUCKET="learn-to-bank.appspot.com"
VITE_FIREBASE_MESSAGING_SENDER_ID="56474464548"
VITE_FIREBASE_APP_ID="1:56474464548:web:af025e45655580c8ac43b1"
VITE_FIREBASE_MEASUREMENT_ID="G-XYLFS0FJP3"
VITE_SESSION_SECRET="Y8o_wB4_3t3YLmqwjK8MEAIzaSyArgMsHrQipci"
VITE_DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiYzQwNTFjODgtNjA5YS00MzliLThhMGUtMjgyY2Q4MTEyYTNmIiwidGVuYW50X2lkIjoiZTZjNGI0ODI3ZjA0Mzc0MzY3ODk2ZjgyYWRmZWM5ZjhlZmMyZjg3NGQwOTdiMDAwZTFhMDRkYjc5OTBkYzU0NiIsImludGVybmFsX3NlY3JldCI6IjdiNTZhNDAwLTg0MzktNDUyNi1iOTU3LTg1YTBiYzYyMDZhOSJ9.1n_yGisIUoGstVS8fu5sglTeX6znXtdMnl5y3JhZzhg"
VITE_DIRECT_URL="postgresql://neondb_owner:h82SkJxWXqsY@ep-still-fire-a711028j-pooler.ap-southeast-2.aws.neon.tech/neondb?sslmode=require"

######## PRODUCTION environment config ########

[[env.production.kv_namespaces]]
binding = "firebase_storage"
id = "f2826afd4c764a229a642e2746c2a1ea"

[env.production.vars]
VITE_FIREBASE_API_KEY="AIzaSyArgMsHrQipciY8o_wB4_3t3YLmqwjK8ME"
VITE_FIREBASE_AUTH_DOMAIN="learn-to-bank.firebaseapp.com"
VITE_FIREBASE_PROJECT_ID="learn-to-bank"
VITE_FIREBASE_STORAGE_BUCKET="learn-to-bank.appspot.com"
VITE_FIREBASE_MESSAGING_SENDER_ID="56474464548"
VITE_FIREBASE_APP_ID="1:56474464548:web:af025e45655580c8ac43b1"
VITE_FIREBASE_MEASUREMENT_ID="G-XYLFS0FJP3"
VITE_SESSION_SECRET="Y8o_wB4_3t3YLmqwjK8MEAIzaSyArgMsHrQipci"
VITE_DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiYzQwNTFjODgtNjA5YS00MzliLThhMGUtMjgyY2Q4MTEyYTNmIiwidGVuYW50X2lkIjoiZTZjNGI0ODI3ZjA0Mzc0MzY3ODk2ZjgyYWRmZWM5ZjhlZmMyZjg3NGQwOTdiMDAwZTFhMDRkYjc5OTBkYzU0NiIsImludGVybmFsX3NlY3JldCI6IjdiNTZhNDAwLTg0MzktNDUyNi1iOTU3LTg1YTBiYzYyMDZhOSJ9.1n_yGisIUoGstVS8fu5sglTeX6znXtdMnl5y3JhZzhg"
VITE_DIRECT_URL="postgresql://neondb_owner:h82SkJxWXqsY@ep-still-fire-a711028j-pooler.ap-southeast-2.aws.neon.tech/neondb?sslmode=require"

[[env.production.d1_databases]]
binding = "DB"
database_name = "learn-to-bank"
database_id = "9a1156c4-12e9-4292-8ab3-198355650df6"
