name: Deploy to Cloudflare Pages

on:
  push:
    branches: [chore/fix-deploy]
  pull_request:
    branches: [chore/fix-deploy]

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    environment: production

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      # Clean up node_modules and install dependencies
      - name: Clean Install
        run: |
          rm -rf node_modules package-lock.json
          npm install

      - name: Install Dependencies
        run: npm ci

      # Method : Using write-file action to restore wrangler.toml
      - name: Restore wrangler.toml (write-file)
        uses: DamianReeves/write-file-action@master
        with:
          path: wrangler.toml
          contents: ${{ secrets.WRANGLER_TOML }}
          write-mode: overwrite

      - name: Build
        run: npm run build

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy ./build/client --project-name=learn-to-bank
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}