name: Deploy to Cloudflare Pages

on:
  push:
    branches: [main]
    paths:
      - 'learn-to-bank-admin-console/**'
      - 'learn-to-bank-cron/**'
      - 'learn-to-bank/**'
  pull_request:
    branches: [main]
    paths:
      - 'learn-to-bank-admin-console/**'
      - 'learn-to-bank-cron/**'
      - 'learn-to-bank/**'

jobs:
  deploy-bank:
    if: github.event.changes && contains(github.event.changes, 'learn-to-bank/')
    runs-on: ubuntu-latest
    name: Deploy Bank App
    environment: production
    defaults:
      run:
        working-directory: ./learn-to-bank

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: ./learn-to-bank/package-lock.json

      # Remove existing node_modules and package-lock.json
      - name: Clean npm cache
        run: |
          rm -rf node_modules
          rm -f package-lock.json

      - name: Install Dependencies
        run: npm install

      # Method : Using write-file action to restore wrangler.toml from secrets
      - name: Restore wrangler.toml (write-file)
        uses: DamianReeves/write-file-action@master
        with:
          path: ./learn-to-bank/wrangler.toml
          contents: ${{ secrets.WRANGLER_TOML }}
          write-mode: overwrite

       # Generate Prisma Client
      - name: Generate Prisma Client
        run: npx prisma generate

      - name: Build
        run: npm run build

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy ./build/client --project-name=learn-to-bank
          workingDirectory: ./learn-to-bank
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}

  